// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class AccountDto {
  final String username;
  final String role;
  final String code;

  const AccountDto({
    required this.username,
    required this.role,
    required this.code,
  });

  @override
  int get hashCode => username.hashCode ^ role.hashCode ^ code.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AccountDto &&
          runtimeType == other.runtimeType &&
          username == other.username &&
          role == other.role &&
          code == other.code;
}

class AgentInfoDto {
  final String ip;
  final String hostname;
  final bool isSetup;
  final bool demo;

  const AgentInfoDto({
    required this.ip,
    required this.hostname,
    required this.isSetup,
    required this.demo,
  });

  @override
  int get hashCode =>
      ip.hashCode ^ hostname.hashCode ^ isSetup.hashCode ^ demo.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AgentInfoDto &&
          runtimeType == other.runtimeType &&
          ip == other.ip &&
          hostname == other.hostname &&
          isSetup == other.isSetup &&
          demo == other.demo;
}

class AgentItemDto {
  final String ip;
  final String hostname;
  final String statusLabel;
  final String statusKind;
  final bool connecting;
  final String? fingerprint;

  const AgentItemDto({
    required this.ip,
    required this.hostname,
    required this.statusLabel,
    required this.statusKind,
    required this.connecting,
    this.fingerprint,
  });

  @override
  int get hashCode =>
      ip.hashCode ^
      hostname.hashCode ^
      statusLabel.hashCode ^
      statusKind.hashCode ^
      connecting.hashCode ^
      fingerprint.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AgentItemDto &&
          runtimeType == other.runtimeType &&
          ip == other.ip &&
          hostname == other.hostname &&
          statusLabel == other.statusLabel &&
          statusKind == other.statusKind &&
          connecting == other.connecting &&
          fingerprint == other.fingerprint;
}

class AppInfoDto {
  final String id;
  final String name;
  final String icon;

  const AppInfoDto({required this.id, required this.name, required this.icon});

  @override
  int get hashCode => id.hashCode ^ name.hashCode ^ icon.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AppInfoDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          icon == other.icon;
}

class AppSettingsDto {
  final String theme;
  final int scanPort;
  final int sidebarWidth;
  final String localViewStyle;
  final String sortBy;
  final String sortDir;
  final String groupBy;
  final bool foldersFirst;
  final bool showHidden;
  final bool showExtensions;
  final bool showThumbnails;
  final String sizeUnit;
  final bool calculateFolderSizes;
  final bool singleClickOpen;
  final bool selectOnHover;
  final bool doubleClickBlankGoUp;
  final bool scrollToPreviousFolderOnUp;
  final bool confirmTrash;
  final bool confirmPermanentDelete;
  final bool warnExtensionRename;
  final String defaultTerminal;
  final bool contextOpenTerminal;
  final bool contextCopyPath;
  final bool contextArchive;
  final bool contextSymlink;
  final bool contextPinSidebar;
  final bool nasLazyLoading;
  final int nasPageSize;
  final double uiScale;
  final bool showInfoPane;
  final String infoPaneTab;
  final bool restoreTabsOnStartup;
  final bool toolbarShowViewToggle;
  final bool toolbarShowHiddenToggle;
  final bool toolbarShowFilters;

  const AppSettingsDto({
    required this.theme,
    required this.scanPort,
    required this.sidebarWidth,
    required this.localViewStyle,
    required this.sortBy,
    required this.sortDir,
    required this.groupBy,
    required this.foldersFirst,
    required this.showHidden,
    required this.showExtensions,
    required this.showThumbnails,
    required this.sizeUnit,
    required this.calculateFolderSizes,
    required this.singleClickOpen,
    required this.selectOnHover,
    required this.doubleClickBlankGoUp,
    required this.scrollToPreviousFolderOnUp,
    required this.confirmTrash,
    required this.confirmPermanentDelete,
    required this.warnExtensionRename,
    required this.defaultTerminal,
    required this.contextOpenTerminal,
    required this.contextCopyPath,
    required this.contextArchive,
    required this.contextSymlink,
    required this.contextPinSidebar,
    required this.nasLazyLoading,
    required this.nasPageSize,
    required this.uiScale,
    required this.showInfoPane,
    required this.infoPaneTab,
    required this.restoreTabsOnStartup,
    required this.toolbarShowViewToggle,
    required this.toolbarShowHiddenToggle,
    required this.toolbarShowFilters,
  });

  @override
  int get hashCode =>
      theme.hashCode ^
      scanPort.hashCode ^
      sidebarWidth.hashCode ^
      localViewStyle.hashCode ^
      sortBy.hashCode ^
      sortDir.hashCode ^
      groupBy.hashCode ^
      foldersFirst.hashCode ^
      showHidden.hashCode ^
      showExtensions.hashCode ^
      showThumbnails.hashCode ^
      sizeUnit.hashCode ^
      calculateFolderSizes.hashCode ^
      singleClickOpen.hashCode ^
      selectOnHover.hashCode ^
      doubleClickBlankGoUp.hashCode ^
      scrollToPreviousFolderOnUp.hashCode ^
      confirmTrash.hashCode ^
      confirmPermanentDelete.hashCode ^
      warnExtensionRename.hashCode ^
      defaultTerminal.hashCode ^
      contextOpenTerminal.hashCode ^
      contextCopyPath.hashCode ^
      contextArchive.hashCode ^
      contextSymlink.hashCode ^
      contextPinSidebar.hashCode ^
      nasLazyLoading.hashCode ^
      nasPageSize.hashCode ^
      uiScale.hashCode ^
      showInfoPane.hashCode ^
      infoPaneTab.hashCode ^
      restoreTabsOnStartup.hashCode ^
      toolbarShowViewToggle.hashCode ^
      toolbarShowHiddenToggle.hashCode ^
      toolbarShowFilters.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AppSettingsDto &&
          runtimeType == other.runtimeType &&
          theme == other.theme &&
          scanPort == other.scanPort &&
          sidebarWidth == other.sidebarWidth &&
          localViewStyle == other.localViewStyle &&
          sortBy == other.sortBy &&
          sortDir == other.sortDir &&
          groupBy == other.groupBy &&
          foldersFirst == other.foldersFirst &&
          showHidden == other.showHidden &&
          showExtensions == other.showExtensions &&
          showThumbnails == other.showThumbnails &&
          sizeUnit == other.sizeUnit &&
          calculateFolderSizes == other.calculateFolderSizes &&
          singleClickOpen == other.singleClickOpen &&
          selectOnHover == other.selectOnHover &&
          doubleClickBlankGoUp == other.doubleClickBlankGoUp &&
          scrollToPreviousFolderOnUp == other.scrollToPreviousFolderOnUp &&
          confirmTrash == other.confirmTrash &&
          confirmPermanentDelete == other.confirmPermanentDelete &&
          warnExtensionRename == other.warnExtensionRename &&
          defaultTerminal == other.defaultTerminal &&
          contextOpenTerminal == other.contextOpenTerminal &&
          contextCopyPath == other.contextCopyPath &&
          contextArchive == other.contextArchive &&
          contextSymlink == other.contextSymlink &&
          contextPinSidebar == other.contextPinSidebar &&
          nasLazyLoading == other.nasLazyLoading &&
          nasPageSize == other.nasPageSize &&
          uiScale == other.uiScale &&
          showInfoPane == other.showInfoPane &&
          infoPaneTab == other.infoPaneTab &&
          restoreTabsOnStartup == other.restoreTabsOnStartup &&
          toolbarShowViewToggle == other.toolbarShowViewToggle &&
          toolbarShowHiddenToggle == other.toolbarShowHiddenToggle &&
          toolbarShowFilters == other.toolbarShowFilters;
}

class ConnectResult {
  final String screen;
  final AgentInfoDto? agent;
  final List<AccountDto> loginAccounts;
  final String? error;

  const ConnectResult({
    required this.screen,
    this.agent,
    required this.loginAccounts,
    this.error,
  });

  @override
  int get hashCode =>
      screen.hashCode ^
      agent.hashCode ^
      loginAccounts.hashCode ^
      error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ConnectResult &&
          runtimeType == other.runtimeType &&
          screen == other.screen &&
          agent == other.agent &&
          loginAccounts == other.loginAccounts &&
          error == other.error;
}

class FetchResponseDto {
  final int status;
  final String body;

  const FetchResponseDto({required this.status, required this.body});

  @override
  int get hashCode => status.hashCode ^ body.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FetchResponseDto &&
          runtimeType == other.runtimeType &&
          status == other.status &&
          body == other.body;
}

class FileHashesDto {
  final String md5;
  final String sha1;
  final String sha256;
  final String crc32;

  const FileHashesDto({
    required this.md5,
    required this.sha1,
    required this.sha256,
    required this.crc32,
  });

  @override
  int get hashCode =>
      md5.hashCode ^ sha1.hashCode ^ sha256.hashCode ^ crc32.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FileHashesDto &&
          runtimeType == other.runtimeType &&
          md5 == other.md5 &&
          sha1 == other.sha1 &&
          sha256 == other.sha256 &&
          crc32 == other.crc32;
}

class FileItemDto {
  final String name;
  final String path;
  final String detail;
  final bool isDir;
  final bool isSymlink;
  final BigInt size;
  final BigInt modifiedSecs;
  final BigInt createdSecs;
  final BigInt accessedSecs;
  final bool isHidden;
  final String? fileExt;
  final String itemType;
  final String parentPath;

  const FileItemDto({
    required this.name,
    required this.path,
    required this.detail,
    required this.isDir,
    required this.isSymlink,
    required this.size,
    required this.modifiedSecs,
    required this.createdSecs,
    required this.accessedSecs,
    required this.isHidden,
    this.fileExt,
    required this.itemType,
    required this.parentPath,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      path.hashCode ^
      detail.hashCode ^
      isDir.hashCode ^
      isSymlink.hashCode ^
      size.hashCode ^
      modifiedSecs.hashCode ^
      createdSecs.hashCode ^
      accessedSecs.hashCode ^
      isHidden.hashCode ^
      fileExt.hashCode ^
      itemType.hashCode ^
      parentPath.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FileItemDto &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          path == other.path &&
          detail == other.detail &&
          isDir == other.isDir &&
          isSymlink == other.isSymlink &&
          size == other.size &&
          modifiedSecs == other.modifiedSecs &&
          createdSecs == other.createdSecs &&
          accessedSecs == other.accessedSecs &&
          isHidden == other.isHidden &&
          fileExt == other.fileExt &&
          itemType == other.itemType &&
          parentPath == other.parentPath;
}

class FileListMetaDto {
  final String currentPath;
  final bool canBack;
  final bool canForward;
  final bool showHidden;
  final String status;

  const FileListMetaDto({
    required this.currentPath,
    required this.canBack,
    required this.canForward,
    required this.showHidden,
    required this.status,
  });

  @override
  int get hashCode =>
      currentPath.hashCode ^
      canBack.hashCode ^
      canForward.hashCode ^
      showHidden.hashCode ^
      status.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FileListMetaDto &&
          runtimeType == other.runtimeType &&
          currentPath == other.currentPath &&
          canBack == other.canBack &&
          canForward == other.canForward &&
          showHidden == other.showHidden &&
          status == other.status;
}

class FilePropertiesDto {
  final String name;
  final String absolutePath;
  final bool isDir;
  final bool isSymlink;
  final String? symlinkTarget;
  final BigInt size;
  final BigInt modifiedSecs;
  final BigInt createdSecs;
  final BigInt accessedSecs;
  final String permissions;
  final String mimeType;

  const FilePropertiesDto({
    required this.name,
    required this.absolutePath,
    required this.isDir,
    required this.isSymlink,
    this.symlinkTarget,
    required this.size,
    required this.modifiedSecs,
    required this.createdSecs,
    required this.accessedSecs,
    required this.permissions,
    required this.mimeType,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      absolutePath.hashCode ^
      isDir.hashCode ^
      isSymlink.hashCode ^
      symlinkTarget.hashCode ^
      size.hashCode ^
      modifiedSecs.hashCode ^
      createdSecs.hashCode ^
      accessedSecs.hashCode ^
      permissions.hashCode ^
      mimeType.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FilePropertiesDto &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          absolutePath == other.absolutePath &&
          isDir == other.isDir &&
          isSymlink == other.isSymlink &&
          symlinkTarget == other.symlinkTarget &&
          size == other.size &&
          modifiedSecs == other.modifiedSecs &&
          createdSecs == other.createdSecs &&
          accessedSecs == other.accessedSecs &&
          permissions == other.permissions &&
          mimeType == other.mimeType;
}

class FileStreamEvent {
  final String eventType;
  final FileItemDto? item;
  final FileListMetaDto? meta;
  final String? message;

  const FileStreamEvent({
    required this.eventType,
    this.item,
    this.meta,
    this.message,
  });

  @override
  int get hashCode =>
      eventType.hashCode ^ item.hashCode ^ meta.hashCode ^ message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FileStreamEvent &&
          runtimeType == other.runtimeType &&
          eventType == other.eventType &&
          item == other.item &&
          meta == other.meta &&
          message == other.message;
}

class FolderSummaryDto {
  final BigInt totalSize;
  final BigInt fileCount;
  final BigInt folderCount;
  final bool truncated;

  const FolderSummaryDto({
    required this.totalSize,
    required this.fileCount,
    required this.folderCount,
    required this.truncated,
  });

  @override
  int get hashCode =>
      totalSize.hashCode ^
      fileCount.hashCode ^
      folderCount.hashCode ^
      truncated.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FolderSummaryDto &&
          runtimeType == other.runtimeType &&
          totalSize == other.totalSize &&
          fileCount == other.fileCount &&
          folderCount == other.folderCount &&
          truncated == other.truncated;
}

class MountEntryDto {
  final String label;
  final String path;
  final String fsType;
  final BigInt totalBytes;
  final BigInt usedBytes;
  final BigInt availableBytes;

  const MountEntryDto({
    required this.label,
    required this.path,
    required this.fsType,
    required this.totalBytes,
    required this.usedBytes,
    required this.availableBytes,
  });

  @override
  int get hashCode =>
      label.hashCode ^
      path.hashCode ^
      fsType.hashCode ^
      totalBytes.hashCode ^
      usedBytes.hashCode ^
      availableBytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MountEntryDto &&
          runtimeType == other.runtimeType &&
          label == other.label &&
          path == other.path &&
          fsType == other.fsType &&
          totalBytes == other.totalBytes &&
          usedBytes == other.usedBytes &&
          availableBytes == other.availableBytes;
}

class PlaceDto {
  final String label;
  final String path;

  const PlaceDto({required this.label, required this.path});

  @override
  int get hashCode => label.hashCode ^ path.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PlaceDto &&
          runtimeType == other.runtimeType &&
          label == other.label &&
          path == other.path;
}

class SearchEntryDto {
  final String name;
  final bool isDir;
  final bool isSymlink;
  final String? targetPath;
  final BigInt size;
  final BigInt modifiedSecs;
  final BigInt createdSecs;
  final BigInt accessedSecs;
  final String absolutePath;
  final bool isHidden;
  final String? fileExt;
  final String itemType;
  final String parentPath;

  const SearchEntryDto({
    required this.name,
    required this.isDir,
    required this.isSymlink,
    this.targetPath,
    required this.size,
    required this.modifiedSecs,
    required this.createdSecs,
    required this.accessedSecs,
    required this.absolutePath,
    required this.isHidden,
    this.fileExt,
    required this.itemType,
    required this.parentPath,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      isDir.hashCode ^
      isSymlink.hashCode ^
      targetPath.hashCode ^
      size.hashCode ^
      modifiedSecs.hashCode ^
      createdSecs.hashCode ^
      accessedSecs.hashCode ^
      absolutePath.hashCode ^
      isHidden.hashCode ^
      fileExt.hashCode ^
      itemType.hashCode ^
      parentPath.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SearchEntryDto &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          isDir == other.isDir &&
          isSymlink == other.isSymlink &&
          targetPath == other.targetPath &&
          size == other.size &&
          modifiedSecs == other.modifiedSecs &&
          createdSecs == other.createdSecs &&
          accessedSecs == other.accessedSecs &&
          absolutePath == other.absolutePath &&
          isHidden == other.isHidden &&
          fileExt == other.fileExt &&
          itemType == other.itemType &&
          parentPath == other.parentPath;
}

class SessionAuthDto {
  final String token;
  final String? macKey;

  const SessionAuthDto({required this.token, this.macKey});

  @override
  int get hashCode => token.hashCode ^ macKey.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SessionAuthDto &&
          runtimeType == other.runtimeType &&
          token == other.token &&
          macKey == other.macKey;
}

class SessionDto {
  final String username;
  final String role;
  final bool isAdmin;

  const SessionDto({
    required this.username,
    required this.role,
    required this.isAdmin,
  });

  @override
  int get hashCode => username.hashCode ^ role.hashCode ^ isAdmin.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SessionDto &&
          runtimeType == other.runtimeType &&
          username == other.username &&
          role == other.role &&
          isAdmin == other.isAdmin;
}

class SetupStateDto {
  final int step;
  final String stepTitle;
  final String stepDesc;
  final String friendlyName;
  final String adminUsername;
  final String adminCode;
  final List<String> watchedPaths;
  final bool excludeHidden;
  final List<String> exclusionPatterns;
  final List<SetupUserDto> users;
  final String manageUsername;
  final String managePassword;
  final String confirmSummary;

  const SetupStateDto({
    required this.step,
    required this.stepTitle,
    required this.stepDesc,
    required this.friendlyName,
    required this.adminUsername,
    required this.adminCode,
    required this.watchedPaths,
    required this.excludeHidden,
    required this.exclusionPatterns,
    required this.users,
    required this.manageUsername,
    required this.managePassword,
    required this.confirmSummary,
  });

  @override
  int get hashCode =>
      step.hashCode ^
      stepTitle.hashCode ^
      stepDesc.hashCode ^
      friendlyName.hashCode ^
      adminUsername.hashCode ^
      adminCode.hashCode ^
      watchedPaths.hashCode ^
      excludeHidden.hashCode ^
      exclusionPatterns.hashCode ^
      users.hashCode ^
      manageUsername.hashCode ^
      managePassword.hashCode ^
      confirmSummary.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SetupStateDto &&
          runtimeType == other.runtimeType &&
          step == other.step &&
          stepTitle == other.stepTitle &&
          stepDesc == other.stepDesc &&
          friendlyName == other.friendlyName &&
          adminUsername == other.adminUsername &&
          adminCode == other.adminCode &&
          watchedPaths == other.watchedPaths &&
          excludeHidden == other.excludeHidden &&
          exclusionPatterns == other.exclusionPatterns &&
          users == other.users &&
          manageUsername == other.manageUsername &&
          managePassword == other.managePassword &&
          confirmSummary == other.confirmSummary;
}

class SetupUserDto {
  final String username;
  final String code;
  final List<String> allowedPaths;

  const SetupUserDto({
    required this.username,
    required this.code,
    required this.allowedPaths,
  });

  @override
  int get hashCode => username.hashCode ^ code.hashCode ^ allowedPaths.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SetupUserDto &&
          runtimeType == other.runtimeType &&
          username == other.username &&
          code == other.code &&
          allowedPaths == other.allowedPaths;
}

class VolumeInfoDto {
  final String mountPath;
  final String device;
  final String fsType;
  final BigInt totalBytes;
  final BigInt usedBytes;
  final BigInt availableBytes;

  const VolumeInfoDto({
    required this.mountPath,
    required this.device,
    required this.fsType,
    required this.totalBytes,
    required this.usedBytes,
    required this.availableBytes,
  });

  @override
  int get hashCode =>
      mountPath.hashCode ^
      device.hashCode ^
      fsType.hashCode ^
      totalBytes.hashCode ^
      usedBytes.hashCode ^
      availableBytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VolumeInfoDto &&
          runtimeType == other.runtimeType &&
          mountPath == other.mountPath &&
          device == other.device &&
          fsType == other.fsType &&
          totalBytes == other.totalBytes &&
          usedBytes == other.usedBytes &&
          availableBytes == other.availableBytes;
}
