// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/datieve.dart';
import 'api/fs.dart';
import 'bridge.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  RustStreamSink<String> dco_decode_StreamSink_String_Sse(dynamic raw);

  @protected
  RustStreamSink<FileStreamEvent> dco_decode_StreamSink_file_stream_event_Sse(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AccountDto dco_decode_account_dto(dynamic raw);

  @protected
  AgentInfoDto dco_decode_agent_info_dto(dynamic raw);

  @protected
  AgentItemDto dco_decode_agent_item_dto(dynamic raw);

  @protected
  AppInfoDto dco_decode_app_info_dto(dynamic raw);

  @protected
  AppSettingsDto dco_decode_app_settings_dto(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  AgentInfoDto dco_decode_box_autoadd_agent_info_dto(dynamic raw);

  @protected
  AppSettingsDto dco_decode_box_autoadd_app_settings_dto(dynamic raw);

  @protected
  FileItemDto dco_decode_box_autoadd_file_item_dto(dynamic raw);

  @protected
  FileListMetaDto dco_decode_box_autoadd_file_list_meta_dto(dynamic raw);

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw);

  @protected
  SessionAuthDto dco_decode_box_autoadd_session_auth_dto(dynamic raw);

  @protected
  SessionDto dco_decode_box_autoadd_session_dto(dynamic raw);

  @protected
  SetupStateDto dco_decode_box_autoadd_setup_state_dto(dynamic raw);

  @protected
  ConnectResult dco_decode_connect_result(dynamic raw);

  @protected
  double dco_decode_f_32(dynamic raw);

  @protected
  FetchResponseDto dco_decode_fetch_response_dto(dynamic raw);

  @protected
  FileHashesDto dco_decode_file_hashes_dto(dynamic raw);

  @protected
  FileItemDto dco_decode_file_item_dto(dynamic raw);

  @protected
  FileListMetaDto dco_decode_file_list_meta_dto(dynamic raw);

  @protected
  FilePropertiesDto dco_decode_file_properties_dto(dynamic raw);

  @protected
  FileStreamEvent dco_decode_file_stream_event(dynamic raw);

  @protected
  FolderSummaryDto dco_decode_folder_summary_dto(dynamic raw);

  @protected
  FsBatchError dco_decode_fs_batch_error(dynamic raw);

  @protected
  FsBatchResult dco_decode_fs_batch_result(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<AccountDto> dco_decode_list_account_dto(dynamic raw);

  @protected
  List<AgentItemDto> dco_decode_list_agent_item_dto(dynamic raw);

  @protected
  List<AppInfoDto> dco_decode_list_app_info_dto(dynamic raw);

  @protected
  List<FsBatchError> dco_decode_list_fs_batch_error(dynamic raw);

  @protected
  List<MountEntryDto> dco_decode_list_mount_entry_dto(dynamic raw);

  @protected
  List<PlaceDto> dco_decode_list_place_dto(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<SearchEntryDto> dco_decode_list_search_entry_dto(dynamic raw);

  @protected
  List<SetupUserDto> dco_decode_list_setup_user_dto(dynamic raw);

  @protected
  MountEntryDto dco_decode_mount_entry_dto(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  AgentInfoDto? dco_decode_opt_box_autoadd_agent_info_dto(dynamic raw);

  @protected
  FileItemDto? dco_decode_opt_box_autoadd_file_item_dto(dynamic raw);

  @protected
  FileListMetaDto? dco_decode_opt_box_autoadd_file_list_meta_dto(dynamic raw);

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw);

  @protected
  SessionAuthDto? dco_decode_opt_box_autoadd_session_auth_dto(dynamic raw);

  @protected
  SessionDto? dco_decode_opt_box_autoadd_session_dto(dynamic raw);

  @protected
  PlaceDto dco_decode_place_dto(dynamic raw);

  @protected
  SearchEntryDto dco_decode_search_entry_dto(dynamic raw);

  @protected
  SessionAuthDto dco_decode_session_auth_dto(dynamic raw);

  @protected
  SessionDto dco_decode_session_dto(dynamic raw);

  @protected
  SetupStateDto dco_decode_setup_state_dto(dynamic raw);

  @protected
  SetupUserDto dco_decode_setup_user_dto(dynamic raw);

  @protected
  int dco_decode_u_16(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  VolumeInfoDto dco_decode_volume_info_dto(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  RustStreamSink<String> sse_decode_StreamSink_String_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<FileStreamEvent> sse_decode_StreamSink_file_stream_event_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AccountDto sse_decode_account_dto(SseDeserializer deserializer);

  @protected
  AgentInfoDto sse_decode_agent_info_dto(SseDeserializer deserializer);

  @protected
  AgentItemDto sse_decode_agent_item_dto(SseDeserializer deserializer);

  @protected
  AppInfoDto sse_decode_app_info_dto(SseDeserializer deserializer);

  @protected
  AppSettingsDto sse_decode_app_settings_dto(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  AgentInfoDto sse_decode_box_autoadd_agent_info_dto(
    SseDeserializer deserializer,
  );

  @protected
  AppSettingsDto sse_decode_box_autoadd_app_settings_dto(
    SseDeserializer deserializer,
  );

  @protected
  FileItemDto sse_decode_box_autoadd_file_item_dto(
    SseDeserializer deserializer,
  );

  @protected
  FileListMetaDto sse_decode_box_autoadd_file_list_meta_dto(
    SseDeserializer deserializer,
  );

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  SessionAuthDto sse_decode_box_autoadd_session_auth_dto(
    SseDeserializer deserializer,
  );

  @protected
  SessionDto sse_decode_box_autoadd_session_dto(SseDeserializer deserializer);

  @protected
  SetupStateDto sse_decode_box_autoadd_setup_state_dto(
    SseDeserializer deserializer,
  );

  @protected
  ConnectResult sse_decode_connect_result(SseDeserializer deserializer);

  @protected
  double sse_decode_f_32(SseDeserializer deserializer);

  @protected
  FetchResponseDto sse_decode_fetch_response_dto(SseDeserializer deserializer);

  @protected
  FileHashesDto sse_decode_file_hashes_dto(SseDeserializer deserializer);

  @protected
  FileItemDto sse_decode_file_item_dto(SseDeserializer deserializer);

  @protected
  FileListMetaDto sse_decode_file_list_meta_dto(SseDeserializer deserializer);

  @protected
  FilePropertiesDto sse_decode_file_properties_dto(
    SseDeserializer deserializer,
  );

  @protected
  FileStreamEvent sse_decode_file_stream_event(SseDeserializer deserializer);

  @protected
  FolderSummaryDto sse_decode_folder_summary_dto(SseDeserializer deserializer);

  @protected
  FsBatchError sse_decode_fs_batch_error(SseDeserializer deserializer);

  @protected
  FsBatchResult sse_decode_fs_batch_result(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<AccountDto> sse_decode_list_account_dto(SseDeserializer deserializer);

  @protected
  List<AgentItemDto> sse_decode_list_agent_item_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<AppInfoDto> sse_decode_list_app_info_dto(SseDeserializer deserializer);

  @protected
  List<FsBatchError> sse_decode_list_fs_batch_error(
    SseDeserializer deserializer,
  );

  @protected
  List<MountEntryDto> sse_decode_list_mount_entry_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<PlaceDto> sse_decode_list_place_dto(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<SearchEntryDto> sse_decode_list_search_entry_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<SetupUserDto> sse_decode_list_setup_user_dto(
    SseDeserializer deserializer,
  );

  @protected
  MountEntryDto sse_decode_mount_entry_dto(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  AgentInfoDto? sse_decode_opt_box_autoadd_agent_info_dto(
    SseDeserializer deserializer,
  );

  @protected
  FileItemDto? sse_decode_opt_box_autoadd_file_item_dto(
    SseDeserializer deserializer,
  );

  @protected
  FileListMetaDto? sse_decode_opt_box_autoadd_file_list_meta_dto(
    SseDeserializer deserializer,
  );

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  SessionAuthDto? sse_decode_opt_box_autoadd_session_auth_dto(
    SseDeserializer deserializer,
  );

  @protected
  SessionDto? sse_decode_opt_box_autoadd_session_dto(
    SseDeserializer deserializer,
  );

  @protected
  PlaceDto sse_decode_place_dto(SseDeserializer deserializer);

  @protected
  SearchEntryDto sse_decode_search_entry_dto(SseDeserializer deserializer);

  @protected
  SessionAuthDto sse_decode_session_auth_dto(SseDeserializer deserializer);

  @protected
  SessionDto sse_decode_session_dto(SseDeserializer deserializer);

  @protected
  SetupStateDto sse_decode_setup_state_dto(SseDeserializer deserializer);

  @protected
  SetupUserDto sse_decode_setup_user_dto(SseDeserializer deserializer);

  @protected
  int sse_decode_u_16(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  VolumeInfoDto sse_decode_volume_info_dto(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_String_Sse(
    RustStreamSink<String> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_file_stream_event_Sse(
    RustStreamSink<FileStreamEvent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_account_dto(AccountDto self, SseSerializer serializer);

  @protected
  void sse_encode_agent_info_dto(AgentInfoDto self, SseSerializer serializer);

  @protected
  void sse_encode_agent_item_dto(AgentItemDto self, SseSerializer serializer);

  @protected
  void sse_encode_app_info_dto(AppInfoDto self, SseSerializer serializer);

  @protected
  void sse_encode_app_settings_dto(
    AppSettingsDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_agent_info_dto(
    AgentInfoDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_app_settings_dto(
    AppSettingsDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_file_item_dto(
    FileItemDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_file_list_meta_dto(
    FileListMetaDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_session_auth_dto(
    SessionAuthDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_session_dto(
    SessionDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_setup_state_dto(
    SetupStateDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_connect_result(ConnectResult self, SseSerializer serializer);

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_fetch_response_dto(
    FetchResponseDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_file_hashes_dto(FileHashesDto self, SseSerializer serializer);

  @protected
  void sse_encode_file_item_dto(FileItemDto self, SseSerializer serializer);

  @protected
  void sse_encode_file_list_meta_dto(
    FileListMetaDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_file_properties_dto(
    FilePropertiesDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_file_stream_event(
    FileStreamEvent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_folder_summary_dto(
    FolderSummaryDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_fs_batch_error(FsBatchError self, SseSerializer serializer);

  @protected
  void sse_encode_fs_batch_result(FsBatchResult self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_account_dto(
    List<AccountDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_agent_item_dto(
    List<AgentItemDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_app_info_dto(
    List<AppInfoDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_fs_batch_error(
    List<FsBatchError> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_mount_entry_dto(
    List<MountEntryDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_place_dto(List<PlaceDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_search_entry_dto(
    List<SearchEntryDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_setup_user_dto(
    List<SetupUserDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_mount_entry_dto(MountEntryDto self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_agent_info_dto(
    AgentInfoDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_file_item_dto(
    FileItemDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_file_list_meta_dto(
    FileListMetaDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_session_auth_dto(
    SessionAuthDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_session_dto(
    SessionDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_place_dto(PlaceDto self, SseSerializer serializer);

  @protected
  void sse_encode_search_entry_dto(
    SearchEntryDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_session_auth_dto(
    SessionAuthDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_session_dto(SessionDto self, SseSerializer serializer);

  @protected
  void sse_encode_setup_state_dto(SetupStateDto self, SseSerializer serializer);

  @protected
  void sse_encode_setup_user_dto(SetupUserDto self, SseSerializer serializer);

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_volume_info_dto(VolumeInfoDto self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
