import '../src/rust/bridge.dart';

extension AppSettingsCopy on AppSettingsDto {
  AppSettingsDto copyWith({
    String? theme,
    int? scanPort,
    int? sidebarWidth,
    String? localViewStyle,
    String? sortBy,
    String? sortDir,
    String? groupBy,
    bool? foldersFirst,
    bool? showHidden,
    bool? showExtensions,
    bool? showThumbnails,
    String? sizeUnit,
    bool? calculateFolderSizes,
    bool? singleClickOpen,
    bool? selectOnHover,
    bool? doubleClickBlankGoUp,
    bool? scrollToPreviousFolderOnUp,
    bool? confirmTrash,
    bool? confirmPermanentDelete,
    bool? warnExtensionRename,
    String? defaultTerminal,
    bool? contextOpenTerminal,
    bool? contextCopyPath,
    bool? contextArchive,
    bool? contextSymlink,
    bool? contextPinSidebar,
    bool? nasLazyLoading,
    int? nasPageSize,
    double? uiScale,
    bool? showInfoPane,
    String? infoPaneTab,
    bool? restoreTabsOnStartup,
    bool? toolbarShowViewToggle,
    bool? toolbarShowHiddenToggle,
    bool? toolbarShowFilters,
  }) {
    return AppSettingsDto(
      theme: theme ?? this.theme,
      scanPort: scanPort ?? this.scanPort,
      sidebarWidth: sidebarWidth ?? this.sidebarWidth,
      localViewStyle: localViewStyle ?? this.localViewStyle,
      sortBy: sortBy ?? this.sortBy,
      sortDir: sortDir ?? this.sortDir,
      groupBy: groupBy ?? this.groupBy,
      foldersFirst: foldersFirst ?? this.foldersFirst,
      showHidden: showHidden ?? this.showHidden,
      showExtensions: showExtensions ?? this.showExtensions,
      showThumbnails: showThumbnails ?? this.showThumbnails,
      sizeUnit: sizeUnit ?? this.sizeUnit,
      calculateFolderSizes: calculateFolderSizes ?? this.calculateFolderSizes,
      singleClickOpen: singleClickOpen ?? this.singleClickOpen,
      selectOnHover: selectOnHover ?? this.selectOnHover,
      doubleClickBlankGoUp: doubleClickBlankGoUp ?? this.doubleClickBlankGoUp,
      scrollToPreviousFolderOnUp:
          scrollToPreviousFolderOnUp ?? this.scrollToPreviousFolderOnUp,
      confirmTrash: confirmTrash ?? this.confirmTrash,
      confirmPermanentDelete:
          confirmPermanentDelete ?? this.confirmPermanentDelete,
      warnExtensionRename: warnExtensionRename ?? this.warnExtensionRename,
      defaultTerminal: defaultTerminal ?? this.defaultTerminal,
      contextOpenTerminal: contextOpenTerminal ?? this.contextOpenTerminal,
      contextCopyPath: contextCopyPath ?? this.contextCopyPath,
      contextArchive: contextArchive ?? this.contextArchive,
      contextSymlink: contextSymlink ?? this.contextSymlink,
      contextPinSidebar: contextPinSidebar ?? this.contextPinSidebar,
      nasLazyLoading: nasLazyLoading ?? this.nasLazyLoading,
      nasPageSize: nasPageSize ?? this.nasPageSize,
      uiScale: uiScale ?? this.uiScale,
      showInfoPane: showInfoPane ?? this.showInfoPane,
      infoPaneTab: infoPaneTab ?? this.infoPaneTab,
      restoreTabsOnStartup:
          restoreTabsOnStartup ?? this.restoreTabsOnStartup,
      toolbarShowViewToggle:
          toolbarShowViewToggle ?? this.toolbarShowViewToggle,
      toolbarShowHiddenToggle:
          toolbarShowHiddenToggle ?? this.toolbarShowHiddenToggle,
      toolbarShowFilters: toolbarShowFilters ?? this.toolbarShowFilters,
    );
  }
}