// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../bridge.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `loopback_fallback_endpoint`

AppSettingsDto getSettings() =>
    RustLib.instance.api.crateApiDatieveGetSettings();

AppSettingsDto saveTheme({required String theme}) =>
    RustLib.instance.api.crateApiDatieveSaveTheme(theme: theme);

AppSettingsDto saveScanPort({required int port}) =>
    RustLib.instance.api.crateApiDatieveSaveScanPort(port: port);

AppSettingsDto saveSettings({required AppSettingsDto settings}) =>
    RustLib.instance.api.crateApiDatieveSaveSettings(settings: settings);

AppSettingsDto resetSettings() =>
    RustLib.instance.api.crateApiDatieveResetSettings();

Future<List<AgentItemDto>> discoverAgents() =>
    RustLib.instance.api.crateApiDatieveDiscoverAgents();

void deletePinnedFingerprint({required String agentIp}) => RustLib.instance.api
    .crateApiDatieveDeletePinnedFingerprint(agentIp: agentIp);

Future<ConnectResult> connectAgent({
  required String ip,
  String? fingerprint,
  required bool skipAutoLogin,
}) => RustLib.instance.api.crateApiDatieveConnectAgent(
  ip: ip,
  fingerprint: fingerprint,
  skipAutoLogin: skipAutoLogin,
);

void disconnectAgent() => RustLib.instance.api.crateApiDatieveDisconnectAgent();

/// Clears the stored session for the current agent without disconnecting.
/// Used for explicit logout: keeps the agent connection so the UI can
/// immediately show the login/account-chooser screen.
void logoutSession() => RustLib.instance.api.crateApiDatieveLogoutSession();

void forgetAccount({required String code}) =>
    RustLib.instance.api.crateApiDatieveForgetAccount(code: code);

Future<SessionDto> loginWithCode({required String code}) =>
    RustLib.instance.api.crateApiDatieveLoginWithCode(code: code);

SetupStateDto getSetupState() =>
    RustLib.instance.api.crateApiDatieveGetSetupState();

SetupStateDto updateSetupState({required SetupStateDto state}) =>
    RustLib.instance.api.crateApiDatieveUpdateSetupState(state: state);

SetupStateDto setupNextStep() =>
    RustLib.instance.api.crateApiDatieveSetupNextStep();

SetupStateDto setupPrevStep() =>
    RustLib.instance.api.crateApiDatieveSetupPrevStep();

Future<void> setupFinalize() =>
    RustLib.instance.api.crateApiDatieveSetupFinalize();

List<PlaceDto> getPlaces() => RustLib.instance.api.crateApiDatieveGetPlaces();

List<MountEntryDto> getMounts() =>
    RustLib.instance.api.crateApiDatieveGetMounts();

String? getTrashPath() => RustLib.instance.api.crateApiDatieveGetTrashPath();

String getViewMode() => RustLib.instance.api.crateApiDatieveGetViewMode();

String setViewMode({required String mode}) =>
    RustLib.instance.api.crateApiDatieveSetViewMode(mode: mode);

Stream<FileStreamEvent> streamLocalFiles() =>
    RustLib.instance.api.crateApiDatieveStreamLocalFiles();

Stream<FileStreamEvent> streamNasFiles({PlatformInt64? parentId}) =>
    RustLib.instance.api.crateApiDatieveStreamNasFiles(parentId: parentId);

Stream<FileStreamEvent> streamNasSearch({required String query}) =>
    RustLib.instance.api.crateApiDatieveStreamNasSearch(query: query);

Stream<FileStreamEvent> streamDemoFiles() =>
    RustLib.instance.api.crateApiDatieveStreamDemoFiles();

FileListMetaDto localNavigate({required String path}) =>
    RustLib.instance.api.crateApiDatieveLocalNavigate(path: path);

FileListMetaDto localBack() => RustLib.instance.api.crateApiDatieveLocalBack();

FileListMetaDto localForward() =>
    RustLib.instance.api.crateApiDatieveLocalForward();

FileListMetaDto localHome() => RustLib.instance.api.crateApiDatieveLocalHome();

FileListMetaDto localToggleHidden() =>
    RustLib.instance.api.crateApiDatieveLocalToggleHidden();

FileListMetaDto openPlace({required String path}) =>
    RustLib.instance.api.crateApiDatieveOpenPlace(path: path);

SessionDto? getSessionInfo() =>
    RustLib.instance.api.crateApiDatieveGetSessionInfo();

AgentInfoDto? getCurrentAgent() =>
    RustLib.instance.api.crateApiDatieveGetCurrentAgent();

SessionAuthDto? getSessionAuth() =>
    RustLib.instance.api.crateApiDatieveGetSessionAuth();

String getLocalCurrentPath() =>
    RustLib.instance.api.crateApiDatieveGetLocalCurrentPath();

Future<FetchResponseDto> agentSecureFetch({
  required String url,
  required String method,
  String? body,
  String? token,
  String? macKey,
}) => RustLib.instance.api.crateApiDatieveAgentSecureFetch(
  url: url,
  method: method,
  body: body,
  token: token,
  macKey: macKey,
);

Stream<String> streamSseEvents({
  required String listenerId,
  required String url,
  String? token,
  String? macKey,
}) => RustLib.instance.api.crateApiDatieveStreamSseEvents(
  listenerId: listenerId,
  url: url,
  token: token,
  macKey: macKey,
);

Future<void> stopSse({String? agent}) =>
    RustLib.instance.api.crateApiDatieveStopSse(agent: agent);

Future<void> demoStartIndex({required String path}) =>
    RustLib.instance.api.crateApiDatieveDemoStartIndex(path: path);
