// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../bridge.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `collect_batch`

void fsCreateDir({required String path}) =>
    RustLib.instance.api.crateApiFsFsCreateDir(path: path);

String fsCreateFile({required String dir, required String name}) =>
    RustLib.instance.api.crateApiFsFsCreateFile(dir: dir, name: name);

String fsCreateTextFile({
  required String dir,
  required String name,
  required String content,
}) => RustLib.instance.api.crateApiFsFsCreateTextFile(
  dir: dir,
  name: name,
  content: content,
);

String fsRename({required String oldPath, required String newName}) =>
    RustLib.instance.api.crateApiFsFsRename(oldPath: oldPath, newName: newName);

List<String> fsBulkRename({
  required List<String> paths,
  required String baseName,
}) => RustLib.instance.api.crateApiFsFsBulkRename(
  paths: paths,
  baseName: baseName,
);

Future<FsBatchResult> fsTrash({required List<String> paths}) =>
    RustLib.instance.api.crateApiFsFsTrash(paths: paths);

void fsRestoreTrash({required List<String> paths}) =>
    RustLib.instance.api.crateApiFsFsRestoreTrash(paths: paths);

void fsEmptyTrash() => RustLib.instance.api.crateApiFsFsEmptyTrash();

Future<FsBatchResult> fsDeletePermanent({required List<String> paths}) =>
    RustLib.instance.api.crateApiFsFsDeletePermanent(paths: paths);

Future<FsBatchResult> fsCopy({
  required List<String> srcPaths,
  required String destDir,
  String? collision,
}) => RustLib.instance.api.crateApiFsFsCopy(
  srcPaths: srcPaths,
  destDir: destDir,
  collision: collision,
);

Future<FsBatchResult> fsMovePaths({
  required List<String> srcPaths,
  required String destDir,
  String? collision,
}) => RustLib.instance.api.crateApiFsFsMovePaths(
  srcPaths: srcPaths,
  destDir: destDir,
  collision: collision,
);

Future<List<String>> fsDuplicate({required List<String> paths}) =>
    RustLib.instance.api.crateApiFsFsDuplicate(paths: paths);

void fsCreateSymlink({required String linkPath, required String target}) =>
    RustLib.instance.api.crateApiFsFsCreateSymlink(
      linkPath: linkPath,
      target: target,
    );

void fsRotateImage({required String path, required String direction}) => RustLib
    .instance
    .api
    .crateApiFsFsRotateImage(path: path, direction: direction);

void fsExtractToSubfolder({required String path}) =>
    RustLib.instance.api.crateApiFsFsExtractToSubfolder(path: path);

Future<void> fsExtractHere({required String path}) =>
    RustLib.instance.api.crateApiFsFsExtractHere(path: path);

Future<void> fsCompress({
  required List<String> paths,
  required String destDir,
  required String format,
}) => RustLib.instance.api.crateApiFsFsCompress(
  paths: paths,
  destDir: destDir,
  format: format,
);

Future<void> openFileNative({required String path}) =>
    RustLib.instance.api.crateApiFsOpenFileNative(path: path);

Future<void> openInTerminal({required String path, String? terminalOverride}) =>
    RustLib.instance.api.crateApiFsOpenInTerminal(
      path: path,
      terminalOverride: terminalOverride,
    );

String? pickFolder() => RustLib.instance.api.crateApiFsPickFolder();

FilePropertiesDto getFileProperties({required String path}) =>
    RustLib.instance.api.crateApiFsGetFileProperties(path: path);

FileHashesDto calculateFileHashes({required String path}) =>
    RustLib.instance.api.crateApiFsCalculateFileHashes(path: path);

VolumeInfoDto getVolumeInfoForPath({required String path}) =>
    RustLib.instance.api.crateApiFsGetVolumeInfoForPath(path: path);

FolderSummaryDto calculateFolderSummary({required String path}) =>
    RustLib.instance.api.crateApiFsCalculateFolderSummary(path: path);

Future<String> readImageThumbnail({required String path}) =>
    RustLib.instance.api.crateApiFsReadImageThumbnail(path: path);

Future<List<SearchEntryDto>> fsSearchRecursive({
  required String root,
  required String query,
  required bool includeHidden,
}) => RustLib.instance.api.crateApiFsFsSearchRecursive(
  root: root,
  query: query,
  includeHidden: includeHidden,
);

void cancelSearch() => RustLib.instance.api.crateApiFsCancelSearch();

List<SearchEntryDto> fsStatPaths({required List<String> paths}) =>
    RustLib.instance.api.crateApiFsFsStatPaths(paths: paths);

String readTextPreview({required String path}) =>
    RustLib.instance.api.crateApiFsReadTextPreview(path: path);

Uint8List readLocalBytes({required String path}) =>
    RustLib.instance.api.crateApiFsReadLocalBytes(path: path);

String getMimeType({required String path}) =>
    RustLib.instance.api.crateApiFsGetMimeType(path: path);

List<AppInfoDto> getAppsForMime({
  required String mimeType,
  required String path,
}) => RustLib.instance.api.crateApiFsGetAppsForMime(
  mimeType: mimeType,
  path: path,
);

Future<void> openWithApp({required String appId, required String path}) =>
    RustLib.instance.api.crateApiFsOpenWithApp(appId: appId, path: path);

void openWithDialogNative({required String path}) =>
    RustLib.instance.api.crateApiFsOpenWithDialogNative(path: path);

class FsBatchError {
  final String path;
  final String error;

  const FsBatchError({required this.path, required this.error});

  @override
  int get hashCode => path.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FsBatchError &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          error == other.error;
}

class FsBatchResult {
  final List<String> succeeded;
  final List<FsBatchError> failed;

  const FsBatchResult({required this.succeeded, required this.failed});

  @override
  int get hashCode => succeeded.hashCode ^ failed.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FsBatchResult &&
          runtimeType == other.runtimeType &&
          succeeded == other.succeeded &&
          failed == other.failed;
}
